import { CardDefinition } from '../types';

export const MAJOR_STARS: CardDefinition[] = [
  {
    id: 'star_ziwei', nameZh: '紫微', category: 'major',
    fiveElement: '土', yinYang: '陰', direction: '中央',
    defaultStrength: '廟', keywords: ['權威', '領導', '尊貴', '帝王'],
    description: '紫微為帝星，主掌權威與領導。代表尊貴、穩重、有統御之才。命逢紫微者，氣度不凡，能掌大局。',
    palaceAssociations: ['命宮', '官祿宮', '福德宮'], symbol: '👑',
  },
  {
    id: 'star_tianji', nameZh: '天機', category: 'major',
    fiveElement: '木', yinYang: '陰', direction: '東南',
    defaultStrength: '旺', keywords: ['智慧', '謀略', '機變', '輔佐'],
    description: '天機為智慧之星，主謀略與變化。善於策劃，心思縝密，能見機行事。',
    palaceAssociations: ['命宮', '福德宮', '遷移宮'], symbol: '🧠',
  },
  {
    id: 'star_taiyang', nameZh: '太陽', category: 'major',
    fiveElement: '火', yinYang: '陽', direction: '南',
    defaultStrength: '廟', keywords: ['光明', '熱情', '博愛', '名望'],
    description: '太陽為光明之星，主熱情與博愛。為人光明磊落，好善樂施，名聲遠播。',
    palaceAssociations: ['命宮', '官祿宮', '交友宮'], symbol: '☀️',
  },
  {
    id: 'star_wuqu', nameZh: '武曲', category: 'major',
    fiveElement: '金', yinYang: '陰', direction: '西',
    defaultStrength: '旺', keywords: ['剛毅', '果斷', '財祿', '武勇'],
    description: '武曲為財星兼武星，主剛毅果斷。做事果決，善理財，有將才之風。',
    palaceAssociations: ['命宮', '財帛宮', '官祿宮'], symbol: '⚔️',
  },
  {
    id: 'star_tiantong', nameZh: '天同', category: 'major',
    fiveElement: '水', yinYang: '陽', direction: '北',
    defaultStrength: '利', keywords: ['溫和', '享福', '協調', '知足'],
    description: '天同為福星，主溫和與享福。性情溫順，知足常樂，善於協調人際。',
    palaceAssociations: ['命宮', '福德宮', '交友宮'], symbol: '🕊️',
  },
  {
    id: 'star_lianzhen', nameZh: '廉貞', category: 'major',
    fiveElement: '火', yinYang: '陰', direction: '南',
    defaultStrength: '陷', keywords: ['剛烈', '執著', '清廉', '刑傷'],
    description: '廉貞為次桃花星，性剛烈執著。清白廉潔，但有時過於剛直易招是非。',
    palaceAssociations: ['命宮', '官祿宮', '疾厄宮'], symbol: '🔥',
  },
  {
    id: 'star_tianfu', nameZh: '天府', category: 'major',
    fiveElement: '土', yinYang: '陽', direction: '中央',
    defaultStrength: '廟', keywords: ['包容', '穩健', '財庫', '忠厚'],
    description: '天府為財庫之星，主包容與穩健。心胸寬大，善於理財積蓄，為人忠厚可靠。',
    palaceAssociations: ['命宮', '財帛宮', '田宅宮'], symbol: '🏛️',
  },
  {
    id: 'star_taiyin', nameZh: '太陰', category: 'major',
    fiveElement: '水', yinYang: '陰', direction: '北',
    defaultStrength: '旺', keywords: ['溫柔', '細膩', '財富', '內斂'],
    description: '太陰為月之精，主溫柔細膩。性情溫婉，心思細密，善積財而不外露。',
    palaceAssociations: ['命宮', '財帛宮', '田宅宮'], symbol: '🌙',
  },
  {
    id: 'star_tanlang', nameZh: '貪狼', category: 'major',
    fiveElement: '木', yinYang: '陽', direction: '東',
    defaultStrength: '利', keywords: ['桃花', '慾望', '才藝', '交際'],
    description: '貪狼為桃花星，主慾望與才藝。多才多藝，擅長交際，但須防貪念。',
    palaceAssociations: ['命宮', '夫妻宮', '交友宮'], symbol: '🐺',
  },
  {
    id: 'star_jumen', nameZh: '巨門', category: 'major',
    fiveElement: '水', yinYang: '陰', direction: '北',
    defaultStrength: '陷', keywords: ['口才', '是非', '深沈', '辯才'],
    description: '巨門為暗星，主口才與是非。能言善道，但易生口舌之爭，須謹言慎行。',
    palaceAssociations: ['命宮', '交友宮', '疾厄宮'], symbol: '🗣️',
  },
  {
    id: 'star_tianxiang', nameZh: '天相', category: 'major',
    fiveElement: '水', yinYang: '陽', direction: '北',
    defaultStrength: '廟', keywords: ['輔佐', '公正', '協調', '服務'],
    description: '天相為印星，主輔佐與公正。善於協調，為人公正無私，是優秀的輔助之才。',
    palaceAssociations: ['命宮', '官祿宮', '交友宮'], symbol: '⚖️',
  },
  {
    id: 'star_tianliang', nameZh: '天梁', category: 'major',
    fiveElement: '土', yinYang: '陽', direction: '中央',
    defaultStrength: '旺', keywords: ['正直', '慈悲', '長壽', '庇佑'],
    description: '天梁為壽星，主正直與慈悲。為人正直不阿，有慈悲心，能逢凶化吉。',
    palaceAssociations: ['命宮', '福德宮', '父母宮'], symbol: '🏛️',
  },
  {
    id: 'star_qisha', nameZh: '七殺', category: 'major',
    fiveElement: '金', yinYang: '陽', direction: '西',
    defaultStrength: '陷', keywords: ['果敢', '冒險', '開創', '剛強'],
    description: '七殺為將星，主果敢與開創。行動力強，敢做敢為，適合開創新局面。',
    palaceAssociations: ['命宮', '官祿宮', '遷移宮'], symbol: '⚔️',
  },
  {
    id: 'star_pojun', nameZh: '破軍', category: 'major',
    fiveElement: '水', yinYang: '陰', direction: '北',
    defaultStrength: '陷', keywords: ['破壞', '革新', '冒險', '變動'],
    description: '破軍為耗星，主破壞與革新。敢於打破舊局，開創新天，但須防冒進之險。',
    palaceAssociations: ['命宮', '遷移宮', '夫妻宮'], symbol: '🌊',
  },
];

export const AUXILIARY_STARS: CardDefinition[] = [
  {
    id: 'star_wenchang', nameZh: '文昌', category: 'auxiliary',
    fiveElement: '金', yinYang: '陽', direction: '西',
    defaultStrength: '廟', keywords: ['文采', '學業', '科名', '才華'],
    description: '文昌主文采科名，利學業考試。文筆出眾，有文學藝術之才。',
    palaceAssociations: ['命宮', '官祿宮', '福德宮'], symbol: '📜',
  },
  {
    id: 'star_wenqu', nameZh: '文曲', category: 'auxiliary',
    fiveElement: '水', yinYang: '陰', direction: '北',
    defaultStrength: '旺', keywords: ['才藝', '口才', '感性', '藝術'],
    description: '文曲主口才與藝術，偏重感性表達。善言辭，有藝術天賦。',
    palaceAssociations: ['命宮', '夫妻宮', '交友宮'], symbol: '🎭',
  },
  {
    id: 'star_zuofu', nameZh: '左輔', category: 'auxiliary',
    fiveElement: '土', yinYang: '陽', direction: '中央',
    defaultStrength: '廟', keywords: ['貴人', '輔助', '助力', '提攜'],
    description: '左輔為貴人星，主得人相助。在事業上常有貴人提攜，化險為夷。',
    palaceAssociations: ['命宮', '官祿宮', '交友宮'], symbol: '🤝',
  },
  {
    id: 'star_youbi', nameZh: '右弼', category: 'auxiliary',
    fiveElement: '水', yinYang: '陰', direction: '北',
    defaultStrength: '廟', keywords: ['輔佐', '智慧', '助力', '暗中相助'],
    description: '右弼同為貴人星，主暗中助力與智慧輔佐。得此星者，常有人幕後相助。',
    palaceAssociations: ['命宮', '官祿宮', '交友宮'], symbol: '🌟',
  },
  {
    id: 'star_tiankui', nameZh: '天魁', category: 'auxiliary',
    fiveElement: '火', yinYang: '陽', direction: '南',
    defaultStrength: '廟', keywords: ['科甲', '貴人', '榮譽', '提拔'],
    description: '天魁為科甲之星，主功名與榮譽。利於考試升遷，得貴人賞識。',
    palaceAssociations: ['命宮', '官祿宮', '福德宮'], symbol: '🏆',
  },
  {
    id: 'star_tianyue', nameZh: '天鉞', category: 'auxiliary',
    fiveElement: '火', yinYang: '陽', direction: '南',
    defaultStrength: '旺', keywords: ['功名', '權威', '成就', '顯達'],
    description: '天鉞主權威與成就，為武貴之星。行動果斷，能建功立業。',
    palaceAssociations: ['命宮', '官祿宮', '遷移宮'], symbol: '🔱',
  },
  {
    id: 'star_lucun', nameZh: '禄存', category: 'auxiliary',
    fiveElement: '土', yinYang: '陽', direction: '中央',
    defaultStrength: '廟', keywords: ['財祿', '積蓄', '穩定', '福報'],
    description: '祿存為財星，主穩定財源與積蓄。財運穩定，不愁衣食。',
    palaceAssociations: ['財帛宮', '田宅宮', '福德宮'], symbol: '💰',
  },
  {
    id: 'star_tianma', nameZh: '天馬', category: 'auxiliary',
    fiveElement: '火', yinYang: '陽', direction: '南',
    defaultStrength: '旺', keywords: ['奔波', '變動', '出行', '迅速'],
    description: '天馬主奔波與變動，利外出發展。行動迅速，適合動態行業。',
    palaceAssociations: ['遷移宮', '官祿宮', '命宮'], symbol: '🐴',
  },
  {
    id: 'star_qingyang', nameZh: '擎羊', category: 'auxiliary',
    fiveElement: '金', yinYang: '陽', direction: '西',
    defaultStrength: '陷', keywords: ['剛強', '衝突', '競爭', '刑傷'],
    description: '擎羊為羊刃，主剛強與競爭。性格剛烈，遇事不退，但須防衝突。',
    palaceAssociations: ['疾厄宮', '官祿宮', '命宮'], symbol: '🐏',
  },
  {
    id: 'star_tuoluo', nameZh: '陀羅', category: 'auxiliary',
    fiveElement: '金', yinYang: '陰', direction: '西',
    defaultStrength: '陷', keywords: ['拖延', '糾結', '反覆', '磨難'],
    description: '陀羅主拖延與反覆，凡事進展緩慢。須耐心應對，不可急躁。',
    palaceAssociations: ['疾厄宮', '命宮', '官祿宮'], symbol: '🔄',
  },
  {
    id: 'star_huoxing', nameZh: '火星', category: 'auxiliary',
    fiveElement: '火', yinYang: '陽', direction: '南',
    defaultStrength: '陷', keywords: ['急躁', '爆發', '突變', '熱情'],
    description: '火星主突發與急躁，來得快去得也快。須防衝動行事，宜三思而後行。',
    palaceAssociations: ['疾厄宮', '遷移宮', '命宮'], symbol: '💥',
  },
  {
    id: 'star_lingxing', nameZh: '鈴星', category: 'auxiliary',
    fiveElement: '火', yinYang: '陰', direction: '南',
    defaultStrength: '陷', keywords: ['陰火', '暗中算計', '隱憂', '慢性'],
    description: '鈴星為陰火，主隱憂與暗算。煩惱潛伏，須防小人暗中作祟。',
    palaceAssociations: ['疾厄宮', '交友宮', '命宮'], symbol: '🔔',
  },
  {
    id: 'star_dikong', nameZh: '地空', category: 'auxiliary',
    fiveElement: '火', yinYang: '陰', direction: '南',
    defaultStrength: '陷', keywords: ['空虛', '不實', '幻想', '落空'],
    description: '地空主空虛不實，凡事易成空。須腳踏實地，不可好高騖遠。',
    palaceAssociations: ['福德宮', '財帛宮', '命宮'], symbol: '🌫️',
  },
  {
    id: 'star_dijie', nameZh: '地劫', category: 'auxiliary',
    fiveElement: '火', yinYang: '陰', direction: '南',
    defaultStrength: '陷', keywords: ['劫難', '損失', '波動', '破耗'],
    description: '地劫主劫難與損失，錢財易散。須謹慎理財，防範意外之災。',
    palaceAssociations: ['財帛宮', '疾厄宮', '命宮'], symbol: '⛈️',
  },
];

export const MISCELLANEOUS_STARS: CardDefinition[] = [
  // === 桃花系 ===
  {
    id: 'star_hongluan', nameZh: '紅鸞', category: 'misc',
    fiveElement: '水', yinYang: '陽', direction: '北',
    defaultStrength: '旺', keywords: ['正桃花', '姻緣', '喜慶', '人緣'],
    description: '紅鸞為正桃花星，主姻緣喜慶。感情順遂，人緣佳，有締結良緣之機。',
    palaceAssociations: ['命宮', '夫妻宮', '福德宮'], symbol: '💕',
  },
  {
    id: 'star_tianxi', nameZh: '天喜', category: 'misc',
    fiveElement: '水', yinYang: '陽', direction: '北',
    defaultStrength: '旺', keywords: ['喜事', '姻緣', '懷孕', '慶典'],
    description: '天喜主喜慶之事，利婚姻生育。喜事臨門，增添歡樂氣氛。',
    palaceAssociations: ['夫妻宮', '子女宮', '命宮'], symbol: '🎉',
  },
  {
    id: 'star_tianyao', nameZh: '天姚', category: 'misc',
    fiveElement: '水', yinYang: '陰', direction: '北',
    defaultStrength: '陷', keywords: ['桃花', '誘惑', '風流', '社交'],
    description: '天姚為次桃花星，主風流韻事。社交手腕強，但須防感情糾紛。',
    palaceAssociations: ['命宮', '夫妻宮', '福德宮'], symbol: '💃',
  },
  {
    id: 'star_xianchi', nameZh: '咸池', category: 'misc',
    fiveElement: '水', yinYang: '陰', direction: '北',
    defaultStrength: '陷', keywords: ['桃花煞', '情感', '魅力', '誘惑'],
    description: '咸池為桃花煞星，主情感誘惑。魅力四射但須防爛桃花纏身。',
    palaceAssociations: ['夫妻宮', '命宮', '福德宮'], symbol: '🌸',
  },
  // === 孤寡系 ===
  {
    id: 'star_guchen', nameZh: '孤辰', category: 'misc',
    fiveElement: '火', yinYang: '陽', direction: '南',
    defaultStrength: '陷', keywords: ['孤獨', '獨立', '清高', '寡合'],
    description: '孤辰主孤獨之性，獨立自主。性情清高不群，須注意人際關係。',
    palaceAssociations: ['命宮', '夫妻宮', '父母宮'], symbol: '🏔️',
  },
  {
    id: 'star_guasu', nameZh: '寡宿', category: 'misc',
    fiveElement: '火', yinYang: '陰', direction: '南',
    defaultStrength: '陷', keywords: ['孤寡', '內向', '獨處', '沉靜'],
    description: '寡宿主內向沉靜，喜獨處。感情上須主動以免錯失良緣。',
    palaceAssociations: ['夫妻宮', '命宮', '福德宮'], symbol: '🏕️',
  },
  // === 哭虛系 ===
  {
    id: 'star_tianku', nameZh: '天哭', category: 'misc',
    fiveElement: '金', yinYang: '陰', direction: '西',
    defaultStrength: '陷', keywords: ['悲傷', '憂愁', '哀怨', '傷感'],
    description: '天哭主憂愁悲傷，情緒易低落。須學習釋放負面情緒，保持正向。',
    palaceAssociations: ['福德宮', '命宮', '疾厄宮'], symbol: '😢',
  },
  {
    id: 'star_tianxu', nameZh: '天虛', category: 'misc',
    fiveElement: '金', yinYang: '陰', direction: '西',
    defaultStrength: '陷', keywords: ['虛弱', '空虛', '消耗', '無力'],
    description: '天虛主虛弱空虛，精力易耗。宜休養生息，積蓄能量。',
    palaceAssociations: ['疾厄宮', '福德宮', '命宮'], symbol: '💨',
  },
  // === 龍鳳系 ===
  {
    id: 'star_longchi', nameZh: '龍池', category: 'misc',
    fiveElement: '水', yinYang: '陽', direction: '北',
    defaultStrength: '廟', keywords: ['才華', '名望', '高雅', '貴氣'],
    description: '龍池主才華與貴氣，有文藝天賦。高雅出眾，受人敬重。',
    palaceAssociations: ['命宮', '官祿宮', '福德宮'], symbol: '🐉',
  },
  {
    id: 'star_fengge', nameZh: '鳳閣', category: 'misc',
    fiveElement: '火', yinYang: '陰', direction: '南',
    defaultStrength: '廟', keywords: ['美感', '藝術', '精緻', '品味'],
    description: '鳳閣主美感與藝術品味。審美觀高雅，在藝術領域有所表現。',
    palaceAssociations: ['命宮', '夫妻宮', '福德宮'], symbol: '🐦',
  },
  // === 三台八座 ===
  {
    id: 'star_santai', nameZh: '三台', category: 'misc',
    fiveElement: '土', yinYang: '陽', direction: '中央',
    defaultStrength: '廟', keywords: ['地位', '名位', '官祿', '榮耀'],
    description: '三台主官位與地位，利事業升遷。名望地位皆有上升之勢。',
    palaceAssociations: ['官祿宮', '命宮', '遷移宮'], symbol: '🏅',
  },
  {
    id: 'star_bazuo', nameZh: '八座', category: 'misc',
    fiveElement: '土', yinYang: '陽', direction: '中央',
    defaultStrength: '旺', keywords: ['地位', '權力', '尊榮', '晉升'],
    description: '八座同主官位權力，利公職人士。權勢地位穩固上升。',
    palaceAssociations: ['官祿宮', '命宮', '福德宮'], symbol: '🎖️',
  },
  // === 恩光天貴 ===
  {
    id: 'star_enguang', nameZh: '恩光', category: 'misc',
    fiveElement: '火', yinYang: '陽', direction: '南',
    defaultStrength: '廟', keywords: ['恩寵', '光榮', '賞識', '提拔'],
    description: '恩光主上輩恩寵與賞識。得長官貴人提拔，事業順利。',
    palaceAssociations: ['官祿宮', '命宮', '父母宮'], symbol: '✨',
  },
  {
    id: 'star_tiangui', nameZh: '天貴', category: 'misc',
    fiveElement: '土', yinYang: '陽', direction: '中央',
    defaultStrength: '廟', keywords: ['貴氣', '榮耀', '尊貴', '提拔'],
    description: '天貴主貴氣與榮耀。受人尊敬，天生帶有貴人運。',
    palaceAssociations: ['命宮', '官祿宮', '福德宮'], symbol: '👑',
  },
  // === 台輔封誥 ===
  {
    id: 'star_taifu', nameZh: '台輔', category: 'misc',
    fiveElement: '土', yinYang: '陽', direction: '中央',
    defaultStrength: '旺', keywords: ['輔佐', '職位', '升遷', '支持'],
    description: '台輔主輔佐職位，善於協助他人。在組織中擔任重要輔助角色。',
    palaceAssociations: ['官祿宮', '命宮', '交友宮'], symbol: '📋',
  },
  {
    id: 'star_fenggao', nameZh: '封誥', category: 'misc',
    fiveElement: '金', yinYang: '陽', direction: '西',
    defaultStrength: '廟', keywords: ['誥命', '榮譽', '褒獎', '認可'],
    description: '封誥主榮譽與褒獎。獲得正式認可與肯定，名正言順。',
    palaceAssociations: ['官祿宮', '命宮', '父母宮'], symbol: '📜',
  },
  // === 天官天福 ===
  {
    id: 'star_tianguan', nameZh: '天官', category: 'misc',
    fiveElement: '火', yinYang: '陽', direction: '南',
    defaultStrength: '廟', keywords: ['官運', '仕途', '功名', '權位'],
    description: '天官主官運仕途，利公職與管理職。事業有權位提升之機。',
    palaceAssociations: ['官祿宮', '命宮', '遷移宮'], symbol: '🏛️',
  },
  {
    id: 'star_tianfu_misc', nameZh: '天福', category: 'misc',
    fiveElement: '木', yinYang: '陽', direction: '東',
    defaultStrength: '廟', keywords: ['福氣', '幸運', '享福', '安樂'],
    description: '天福主福氣與幸運。天賜之福，生活安樂，化險為夷。',
    palaceAssociations: ['福德宮', '命宮', '田宅宮'], symbol: '🍀',
  },
  // === 天才天壽 ===
  {
    id: 'star_tiancai', nameZh: '天才', category: 'misc',
    fiveElement: '木', yinYang: '陽', direction: '東',
    defaultStrength: '旺', keywords: ['天賦', '聰明', '創意', '靈感'],
    description: '天才主天賦與聰明才智。有過人智慧，創意靈感源源不絕。',
    palaceAssociations: ['命宮', '福德宮', '官祿宮'], symbol: '💡',
  },
  {
    id: 'star_tianshou', nameZh: '天壽', category: 'misc',
    fiveElement: '土', yinYang: '陽', direction: '中央',
    defaultStrength: '廟', keywords: ['長壽', '健康', '耐久', '穩健'],
    description: '天壽主長壽與健康耐久。身體基底好，處事穩健持久。',
    palaceAssociations: ['疾厄宮', '福德宮', '命宮'], symbol: '🧓',
  },
  // === 煞星雜曜（含用戶指定的陰煞、蜚蠊） ===
  {
    id: 'star_yinsha', nameZh: '陰煞', category: 'misc',
    fiveElement: '水', yinYang: '陰', direction: '北',
    defaultStrength: '陷', keywords: ['暗算', '小人', '陰謀', '隱患'],
    description: '陰煞為暗中之煞，主小人暗算與陰謀。須謹慎提防，不可輕信他人。',
    palaceAssociations: ['疾厄宮', '交友宮', '命宮'], symbol: '👤',
  },
  {
    id: 'star_feilian', nameZh: '蜚蠊', category: 'misc',
    fiveElement: '火', yinYang: '陰', direction: '南',
    defaultStrength: '陷', keywords: ['口舌', '是非', '讒言', '小人'],
    description: '蜚蠊主口舌是非與讒言中傷。慎防小人搬弄是非，言語之爭。',
    palaceAssociations: ['交友宮', '命宮', '疾厄宮'], symbol: '🪳',
  },
  {
    id: 'star_huagai', nameZh: '華蓋', category: 'misc',
    fiveElement: '木', yinYang: '陽', direction: '東',
    defaultStrength: '利', keywords: ['孤高', '才藝', '宗教', '玄學'],
    description: '華蓋主孤高與特殊才華。對宗教玄學有興趣，才藝不凡但略顯孤傲。',
    palaceAssociations: ['命宮', '福德宮', '官祿宮'], symbol: '☂️',
  },
  {
    id: 'star_jiesha', nameZh: '劫煞', category: 'misc',
    fiveElement: '火', yinYang: '陽', direction: '南',
    defaultStrength: '陷', keywords: ['劫難', '搶奪', '意外', '損失'],
    description: '劫煞主意外劫難與損失。凡事需小心防範，遠離是非之地。',
    palaceAssociations: ['疾厄宮', '財帛宮', '命宮'], symbol: '⚡',
  },
  {
    id: 'star_zaisha', nameZh: '災煞', category: 'misc',
    fiveElement: '金', yinYang: '陽', direction: '西',
    defaultStrength: '陷', keywords: ['災難', '橫禍', '病痛', '意外'],
    description: '災煞主災難橫禍。宜多行善積德，注意人身安全。',
    palaceAssociations: ['疾厄宮', '命宮', '遷移宮'], symbol: '⚠️',
  },
  // === 其他雜曜 ===
  {
    id: 'star_jieshen', nameZh: '解神', category: 'misc',
    fiveElement: '水', yinYang: '陽', direction: '北',
    defaultStrength: '廟', keywords: ['化解', '消災', '轉機', '貴人'],
    description: '解神主化解災難與危機。遇到困難時有化解之道，逢凶化吉。',
    palaceAssociations: ['疾厄宮', '福德宮', '命宮'], symbol: '🔑',
  },
  {
    id: 'star_tianxing', nameZh: '天刑', category: 'misc',
    fiveElement: '金', yinYang: '陽', direction: '西',
    defaultStrength: '陷', keywords: ['刑罰', '官司', '紀律', '約束'],
    description: '天刑主刑罰與官司之事。須遵守法紀，避免觸犯規矩。',
    palaceAssociations: ['官祿宮', '疾厄宮', '命宮'], symbol: '⚖️',
  },
  {
    id: 'star_dahao', nameZh: '大耗', category: 'misc',
    fiveElement: '火', yinYang: '陰', direction: '南',
    defaultStrength: '陷', keywords: ['損耗', '破財', '浪費', '消耗'],
    description: '大耗主錢財損耗與浪費。宜節儉理財，避免不必要開銷。',
    palaceAssociations: ['財帛宮', '命宮', '田宅宮'], symbol: '💸',
  },
  {
    id: 'star_tianwu', nameZh: '天巫', category: 'misc',
    fiveElement: '土', yinYang: '陽', direction: '中央',
    defaultStrength: '利', keywords: ['巫醫', '神秘', '靈感', '玄學'],
    description: '天巫主神秘學與靈感。對命理、占卜、醫術有天賦。',
    palaceAssociations: ['福德宮', '命宮', '疾厄宮'], symbol: '🔮',
  },
  {
    id: 'star_longde', nameZh: '龍德', category: 'misc',
    fiveElement: '木', yinYang: '陽', direction: '東',
    defaultStrength: '廟', keywords: ['貴人', '福星', '庇佑', '逢凶化吉'],
    description: '龍德為大吉星，主貴人庇佑。萬事順遂，逢凶化吉。',
    palaceAssociations: ['命宮', '福德宮', '遷移宮'], symbol: '🐲',
  },

];

export const ALL_CARDS: CardDefinition[] = [
  ...MAJOR_STARS,
  ...AUXILIARY_STARS,
  ...MISCELLANEOUS_STARS,
];
